#!/bin/sh
#
# PROVIDE: ddns
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="ddns"
rcvar="ddns_enable"
ddns_user="ddns"
ddns_command="/usr/local/ddns/bin/ddns --config /usr/local/ddns/conf/ddns.yml"
pidfile="/var/run/ddns/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${ddns_command}"

load_rc_config $name
: ${ddns_enable:=no}

run_rc_command "$1"
